name: Feature-Request
description: File a feature request
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: background
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Please describe the problem you are trying to solve.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-you-want
    attributes:
      label: Describe the solution you'd like!
      description: Please describe the desired behavior.
      placeholder: Tell us what you want to see!
      value: "A bug doesn't happen!"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered any alternatives?
      description: Please describe any alternatives you've considered.
      placeholder: Tell us what you've considered!
      value: "I've considered rebuilding the internet"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Developer-DAO/.github)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
